import { RefreshCw, TrendingDown, TrendingUp, Minus } from "lucide-react";
function getRiskClass(category) { const value = (category || "").toUpperCase(); return ["CRITICAL", "HIGH", "MODERATE", "MEDIUM"].includes(value) ? value.toLowerCase().replace("medium", "moderate") : "low"; }
function TrendIcon({ trend }) { return trend === "RISING" ? <TrendingUp size={16} /> : trend === "FALLING" ? <TrendingDown size={16} /> : <Minus size={16} />; }
export default function RiskCard({ risk, loading, onRefresh }) {
  if (loading && !risk) return <div className="risk-card loading-card"><span className="loader" /><p>Loading live risk intelligence…</p></div>;
  if (!risk) return <div className="risk-card unavailable"><p className="card-label">CURRENT FLOOD RISK</p><h2>Data unavailable</h2><p>Risk data will appear when the live prediction service is available.</p></div>;
  const riskClass = getRiskClass(risk.risk_category); const score = Math.max(0, Math.min(Number(risk.risk_score) || 0, 100));
  return <article className={`risk-card ${riskClass}`}><div className="risk-card-top"><div><p className="card-label">ML PREDICTION · CURRENT FLOOD RISK</p><h2>{risk.risk_category}</h2></div><button className="icon-button" onClick={onRefresh} disabled={loading} title="Generate a fresh prediction"><RefreshCw size={18} className={loading ? "spinning" : ""} /></button></div><div className="risk-main"><div className="risk-score"><span>{Math.round(score)}</span><small>/100 risk score</small></div><div className="risk-meter" aria-label={`${score} out of 100`}><div className="risk-meter-fill" style={{ width: `${score}%` }} /></div></div><div className="risk-stats"><div><span>Confidence</span><strong>{Math.round((risk.confidence || 0) * 100)}%</strong></div><div><span>Trend</span><strong className="trend"><TrendIcon trend={risk.trend} />{risk.trend || "STABLE"}</strong></div><div><span>Horizon</span><strong>{risk.forecast_horizon_hours ?? "—"}h</strong></div></div><div className="risk-footer"><span>{risk.is_prototype ? "Prototype model" : "Validated model"}</span><strong>{risk.model_version || "—"}</strong></div></article>;
}
