"""initial schema: core PRAGYA tables

Revision ID: 5106a3cfd9db
Revises: 
Create Date: 2026-08-22 03:15:20.947377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5106a3cfd9db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('input_reference', sa.JSON(), nullable=True),
    sa.Column('output_reference', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('document_versions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellite_observations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=True),
    sa.Column('acquisition_time', sa.DateTime(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('cloud_percentage', sa.Float(), nullable=True),
    sa.Column('image_uri', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # note: GeoAlchemy2 creates the GIST spatial index on 'geometry' automatically
    # via a DDL event when create_table runs, so no explicit create_index here.
    op.create_table('sop_documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('document_uri', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('district_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('vulnerability_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_district_id'), 'zones', ['district_id'], unique=False)
    op.create_table('flood_detections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('zone_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('before_scene_id', sa.String(), nullable=True),
    sa.Column('after_scene_id', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('affected_area', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flood_detections_zone_id'), 'flood_detections', ['zone_id'], unique=False)
    op.create_table('rainfall_observations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('quality_status', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rainfall_observations_zone_id'), 'rainfall_observations', ['zone_id'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('zone_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prediction_time', sa.DateTime(), nullable=True),
    sa.Column('forecast_horizon', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('feature_snapshot_id', sa.String(), nullable=True),
    sa.Column('is_prototype', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_predictions_zone_id'), 'risk_predictions', ['zone_id'], unique=False)
    op.create_table('river_observations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('river_name', sa.String(), nullable=True),
    sa.Column('zone_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('water_level', sa.Float(), nullable=False),
    sa.Column('warning_level', sa.Float(), nullable=True),
    sa.Column('danger_level', sa.Float(), nullable=True),
    sa.Column('rate_of_change', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_river_observations_zone_id'), 'river_observations', ['zone_id'], unique=False)
    op.create_table('sop_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('clause', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['sop_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sop_chunks')
    op.drop_index(op.f('ix_river_observations_zone_id'), table_name='river_observations')
    op.drop_table('river_observations')
    op.drop_index(op.f('ix_risk_predictions_zone_id'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_rainfall_observations_zone_id'), table_name='rainfall_observations')
    op.drop_table('rainfall_observations')
    op.drop_index(op.f('ix_flood_detections_zone_id'), table_name='flood_detections')
    op.drop_table('flood_detections')
    op.drop_index(op.f('ix_zones_district_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_table('sop_documents')
    op.drop_table('satellite_observations')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
